services:
  - type: web
    name: perfum-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: perfum-api.onrender.com,.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: perfum-db
          property: connectionString
    healthCheckPath: /admin/

databases:
  - name: perfum-db
    databaseName: parfum_db
    user: parfum_user